name: example
description: Demo app for the badges package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  badges:
    path: ../

  material_ui: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/getman.jpeg
    - assets/twitter.png
    - assets/instagram.png
